[pytest]
DJANGO_SETTINGS_MODULE = project_name.settings
python_files = tests.py test_*.py *_tests.py
addopts =
    --maxfail=1
    -vv
    --cov=users
    --cov=tasks
    --cov-report=term-missing
    --disable-warnings
    --tb=short