# Generated by Django 6.0.4 on 2026-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('未着手', '未着手'), ('進行中', '進行中'), ('完了', '完了')], default='todo', max_length=20),
        ),
    ]
